venue_cms/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.authentication.urls")),
    path("", include("apps.home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/models.py
from django.conf import settings
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class Campaign(models.Model):
    name = models.CharField(max_length=100)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)

    # TODO: Según el PDF, esto es un ManyToMany
    venues = models.ForeignKey('Venue', on_delete=models.CASCADE, null=True)

    # TODO: Según el PDF, esto es un ManyToMany
    washroom_groups = models.ForeignKey(
        'WashroomGroups', on_delete=models.CASCADE, null=True, related_name='campaigns', blank=True)
    owner = models.ForeignKey(getattr(settings, 'AUTH_USER_MODEL'), on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name) if self.name else "-"

    def get_media(self):
        return self.media_files.all()

    def get_media_urls(self):
        all_urls = []
        for m in self.get_media():
            all_urls.append(getattr(settings, 'HOSTNAME') + m.file.url)

        return all_urls


class Venue(models.Model):
    name = models.CharField(max_length=100)
    address1 = models.CharField(max_length=150)
    address2 = models.CharField(max_length=150, blank=True, null=True)

    country = models.CharField(max_length=100)
    state = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)

    playlist = models.IntegerField(
        default=0, blank=True, null=True,
        help_text='This field is auto-filled with the number of related Campaigns'
    )
    ad_approver = models.CharField(max_length=100, blank=True, null=True)
    phone = PhoneNumberField(blank=True, null=True)
    email = models.EmailField("email address", blank=True, null=True)

    contract_start = models.DateField(blank=True, null=True)
    contract_end = models.DateField(blank=True, null=True)

    loop_size = models.IntegerField(default=0)
    max_ad_time = models.TimeField(blank=True, null=True)

    owner = models.ForeignKey(getattr(settings, 'AUTH_USER_MODEL'), on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name) if self.name else "-"


class WashroomGroups(models.Model):
    name = models.CharField(max_length=100, default="Washroom Group v1")
    # washrooms = models.ManyToManyField(to='Washroom', related_name='washroom_group')

    class Meta:
        verbose_name = "Washroom Group"
        verbose_name_plural = "Washroom Groups"

    def __str__(self):
        return "(" + self.name + ")" + " " + self.get_washrooms()

    def get_washrooms(self):
        wlist = []
        if len(self.washrooms.all()) > 0:
            wlist = [f.name for f in self.washrooms.all()]
        wc = wlist if wlist else "not assigned"
        return str(wc)


class Washroom(models.Model):
    GENDERS = (
        ('FAMILY', 'Family'),
        ('FEMALE', 'Female'),
        ('MALE', 'Male'),
    )
    GENDERS_DEFAULT = 'FAMILY'

    gender = models.CharField(
        max_length=25,
        choices=GENDERS,
        default=GENDERS_DEFAULT
    )
    name = models.CharField(max_length=100)
    washroom_groups = models.ForeignKey(
        WashroomGroups, models.CASCADE, null=True, blank=True, related_name="washrooms")
    venues = models.ForeignKey(
        Venue, on_delete=models.CASCADE, related_name='washrooms', null=True)

    def __str__(self):
        return str(self.name) if self.name else "-"


class Faucet(models.Model):
    STATUS = (
        ('ONLINE', 'Online'),
        ('OFFLINE', 'Offline'),
    )
    STATUS_DEFAULT = 'OFFLINE'

    name = models.CharField(max_length=100, blank=True, null=True)
    mac = models.CharField(max_length=100)
    ip_address = models.CharField(max_length=100, blank=True, null=True)
    status = models.CharField(
        choices=STATUS, default=STATUS_DEFAULT,
        max_length=50, blank=True, null=True
    )
    playlist = models.CharField(max_length=100, blank=True, null=True)

    washroom = models.ForeignKey(
        Washroom, on_delete=models.CASCADE, related_name='faucets', null=True)

    owner = models.ForeignKey(
        "users.MacUser", on_delete=models.CASCADE,
        blank=True, null=True
    )

    def __str__(self):
        return str(self.name) if self.name else "-"


class Media(models.Model):
    TYPE = (
        ('VIDEO', 'Video'),
        ('PHOTO', 'Photo'),
    )
    TYPE_DEFAULT = 'VIDEO'

    name = models.CharField(max_length=100)

    file = models.FileField(upload_to='media/', null=True, blank=True)

    campaign = models.ForeignKey(
        Campaign, on_delete=models.CASCADE, null=True, related_name="media_files")
    date_uploaded = models.DateTimeField(auto_now_add=True)
    type = models.CharField(
        max_length=25,
        choices=TYPE,
        default=TYPE_DEFAULT
    )

    def __str__(self):
        return str(self.name) if self.name else "-"

apps/templates/layouts/add-new-record.html
{% extends "layouts/base.html" %}

{% block title %} {{ table_title }} {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
      <div class="col-md-12">
        <div class="card">

          <div class="card-header card-header-primary">
            <h4 class="card-title">{{ segment }}</h4>
          </div>

          <form enctype="multipart/form-data" action="/add/{{ segment }}/new_record" method="post">

            {% csrf_token %}

            <div class="card-body">

              {% if form.errors %}
                <div class="alert alert-danger">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <i class="material-icons">close</i>
                  </button>
                  <span>
                    <b> Warning - </b> {{ form.errors }}
                  </span>
                </div>
              {% endif %}

              <div class="table-responsive">
                  <table class="table">
                    <tbody>
                      {{ form.as_table }}
                    </tbody>
                  </table>
              </div>

            </div>

            <button class="btn btn-primary btn-block" type="submit">Save</button>

          </form>
        </div>
      </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
  $('#id_venues').on('change', function(){
    LoadWashrooms();
  });
{% endblock javascripts %}

apps/templates/layouts/base-tables.html
{% extends "layouts/base.html" %}

{% block title %} {{ table_title }} {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
      <div class="col-md-12">
        <div class="card">

          <div class="card-header card-header-primary">
            <h4 class="card-title">{{ segment }}</h4>
            <p class="card-category">{{ table_subtitle }}</p>
          </div>

          <div class="card-body">
            <div class="table-responsive">
              <table class="table">

                <thead class=" text-primary">
                  {% for head in table_header %}
                    <th>{{ head }}</th>
                  {% endfor %}
                </thead>

                <tbody>
                  {% for body in table_body %}
                    <tr>
                      {% for key, value in body.items %}
                        <td>
                          {% if key == 'Action' %}
                            <a href="/update/{{ segment }}/{{ value }}">Edit</a> | <a href="/delete/{{ segment }}/{{ value }}">Delete</a>
                          {% else %}
                            {{ value }}
                          {% endif %}
                        </td>
                      {% endfor %}
                    </tr>
                  {% endfor %}
                </tbody>

              </table>

            </div>
          </div>
        </div>

        {% if segment in 'washrooms' %}
          <a href="{% url 'add_new_record' model='washroom-groups' %}">
            <button class="btn btn-primary btn-block">New Washroom Group</button>
          </a>
        {% endif %}

      </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/layouts/base.html
<!--
=========================================================
 Material Dashboard - v2.1.2
=========================================================

 Product Page: https://www.creative-tim.com/product/material-dashboard
 Copyright 2019 Creative Tim (https://www.creative-tim.com)
 Licensed under MIT (https://github.com/creativetimofficial/material-dashboard/blob/master/LICENSE.md)

 Coded by Creative Tim

=========================================================

 The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="/static/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="/static/assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <link rel="canonical" href="https://appseed.us/admin-dashboards/django-dashboard-material">

    <title>
      Venue CMS {% block title %}{% endblock %}
    </title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!-- Fonts and icons -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- CSS Files -->
    <link href="/static/assets/css/material-dashboard.css" rel="stylesheet" />
    <link href="/static/assets/css/custom.css" rel="stylesheet" />
    <link href="/static/assets/demo/demo.css" rel="stylesheet" />

    <!-- Specific Page CSS goes HERE  -->
    {% block stylesheets %}{% endblock stylesheets %}

  </head>

  <body class="">
    <div class="wrapper ">

      {% include 'includes/sidebar.html' %}

      <div class="main-panel">

        {% include 'includes/navigation.html' %}

        <!-- End Navbar -->
        <div class="content">
          <div class="container-fluid">

            {% block content %}{% endblock content %}

          </div>
        </div>

        {% include 'includes/footer.html' %}

      </div>
    </div>

    <!-- {% include 'includes/fixed-plugin.html' %} -->

    {% include 'includes/scripts.html' %}

    {% include 'includes/scripts-sidebar.html' %}

    <!-- Specific Page JS goes HERE  -->
    <script>
      {% block javascripts %}{% endblock javascripts %}
      
      function LoadWashrooms()
      {
        var $id_venue = $('#id_venues').val();

        $.ajax({
          method: "GET",
          url: "/get_washrooms/" + $id_venue,
          dataType: 'json',
          data: {},
          success: function(data, status) {

              $("#id_washroom_groups").empty();

              var items = data['washroom_options'];

              $.each(items, function(key, value) {
                $("#id_washroom_groups").append(
                  $('<option>', {
                    value: value.id,
                    text: value.name
                }));
              });

          },
          error: function(response) {}
        });
      }
    </script>

  </body>
</html>

apps/templates/layouts/update-record.html
{% extends "layouts/base.html" %}

{% block title %} {{ table_title }} {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
      <div class="col-md-12">
        <div class="card">

          <div class="card-header card-header-primary">
            <h4 class="card-title">{{ segment }}</h4>
          </div>

          <form action="" method="post">
            {% csrf_token %}

            <div class="card-body">
              <div class="table-responsive">
                  <table class="table">
                    <tbody>
                      {{ form.as_table }}
                    </tbody>
                  </table>
              </div>
            </div>

            <button class="btn btn-primary btn-block" type="submit">Update</button>

          </form>

          {% if segment in 'campaigns' and media|length > 0 %}
            <div class="card-body">
              <div class="table-responsive">

                <h4>Media files for this campaign</h4>
                <ul style="padding-left: 10px;">
                  {% for m in media %}
                    <li style="list-style-type: none;">
                      <a href="/update/media/{{ m.id }}">{{ m.name }}</a>
                    </li>
                  {% endfor %}
                </ul>

              </div>
            </div>
          {% endif %}

        </div>
      </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
  {% if segment in 'campaigns' %}
    $(document).ready(function() {
      LoadWashrooms();
    });

    $('#id_venues').on('change', function(){
      LoadWashrooms();
    });
  {% endif %}
{% endblock javascripts %}